version: '3.8'

services:
  strider-front:
    container_name: strider-front
    build:
      context: .
    ports:
      - 80:3000
    volumes:
      - ./:/code
      - ./node_modules:/code/node_modules
    env_file: .env
