name: Format with Prettier

on:
  pull_request:
    branches:
      - '**'

  push:
    branches:
      - '**'

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.1.1
        with:
          prettier_options: --write **/*.{js,ts,jsx,tsx,css,md,json} --config .prettierrc
